local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("snowy mountain", "Synapse")
local Tab1 = Window:NewTab("Guns")
local Tab2 = Window:NewTab("Ammo")
local Tab3 = Window:NewTab("escape tools")
local Tab6 = Window:NewTab("Team change")
local Tab7 = Window:NewTab("Teleport")
local Tab4 = Window:NewTab("Credit")
local Section1 = Tab1:NewSection("This Sript By KODMSM")
local Section2 = Tab4:NewSection("Discord : Venka#0303")
local Section3 = Tab4:NewSection("ID KODMSM 1652308871")
local Section4 = Tab3:NewSection("It Work sometimes")
local Section5 = Tab2:NewSection("Ammo and Others")
local Section5 = Tab2:NewSection("We apologize for this feature")
local Section6 = Tab6:NewSection("Team Change [SOON]")
local Section7 = Tab7:NewSection("Moving to many places")

Section1:NewToggle("AK-47", "Grab AK-47", function(state)
    local args = {
        [1] = workspace.Prison_ITEMS.giver:FindFirstChild("AK-47").ITEMPICKUP
    }
    
    workspace.Remote.ItemHandler:InvokeServer(unpack(args))
    
    if state then
        print("!p1")
    else
        print("!s1")
    end
end)

Section1:NewToggle("Remington 870", "Gun", function(state)
    local args = {
        [1] = workspace.Prison_ITEMS.giver:FindFirstChild("Remington 870").ITEMPICKUP
    }
    
    workspace.Remote.ItemHandler:InvokeServer(unpack(args))
    
    if state then
        print("!p2")
    else
        print("!s2")
    end
end)

Section1:NewToggle("M9", "M9", function(state)
    local args = {
        [1] = workspace.Prison_ITEMS.giver:FindFirstChild("M9").ITEMPICKUP
    }
    
    workspace.Remote.ItemHandler:InvokeServer(unpack(args))
    
    if state then
        print("!p3")
    else
        print("!s3")
    end
end)

Section1:NewToggle("M4A1 [Game Pass]", "powerful weapon", function(state)
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = workspace.Prison_ITEMS.giver.M4A1.ITEMPICKUP
}

workspace.Remote.ItemHandler:InvokeServer(unpack(args))

    
    if state then
        print("!p")
    else
        print("!s")
    end
end)

Section4:NewToggle("Key Card [sometimes works]", "Key Card Any Door", function(state)
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = workspace.Prison_ITEMS.single:FindFirstChild("Key card").ITEMPICKUP
}

workspace.Remote.ItemHandler:InvokeServer(unpack(args))


-- Script generated by SimpleSpy - credits to exx#9394

function getNil(name,class) for _,v in pairs(getnilinstances())do if v.ClassName==class and v.Name==name then return v;end end end

local args = {
    [1] = getNil("Key card", "Model").ITEMPICKUP
}

workspace.Remote.ItemHandler:InvokeServer(unpack(args))


    if state then
        print("!p4")
    else
        print("!s4")
    end
end)



Section4:NewToggle("Breakfast       [It only works during the day]", "Food", function(state)
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = workspace.Prison_ITEMS.giver.Breakfast.ITEMPICKUP
}

workspace.Remote.ItemHandler:InvokeServer(unpack(args))


    if state then
        print("!p5")
    else
        print("!s5")
    end
end)


Section4:NewToggle("Crude Knife", "... nothing", function(state)
    local args = {
        [1] = workspace.Prison_ITEMS.single:FindFirstChild("Crude Knife").ITEMPICKUP
    }
    
    workspace.Remote.ItemHandler:InvokeServer(unpack(args))
    if state then
        print("!p6")
    else
        print("!s6")
    end
end)



Section4:NewToggle("Hammer", "... nothing2", function(state)
    local args = {
        [1] = workspace.Prison_ITEMS.single:FindFirstChild("Hammer").ITEMPICKUP
    }
    
    workspace.Remote.ItemHandler:InvokeServer(unpack(args))
    if state then
        print("!p7")
    else
        print("!s7")
    end
end)




Section4:NewToggle("Dinner       [It only works during the day]", "Food", function(state)
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = workspace.Prison_ITEMS.giver.Dinner.ITEMPICKUP
}

workspace.Remote.ItemHandler:InvokeServer(unpack(args))

    if state then
        print("!p8")
    else
        print("!s8")
    end
end)

Section7:NewButton("Criminals . headquarters", "Teleport to Criminals . headquarters", function()
    loadstring(game:HttpGet("https://pastebin.com/raw/zXwSA9dW"))();
    
    print("Clicked")
end)

Section7:NewButton("Respawn Car", "Teleport to Respawn Car", function()
    loadstring(game:HttpGet("https://pastebin.com/raw/KUjLUzHP"))();
    
    print("Clicked")
end)

Section7:NewButton("Deserted place [Useless]", "Useless", function()
    loadstring(game:HttpGet("https://pastebin.com/raw/33qtrHhC"))();
    
    print("Clicked")
end)


Section7:NewButton("Narrow building entrance", "Teleport ", function()
    loadstring(game:HttpGet("https://pastebin.com/raw/i9rL6jWM"))();
    
    print("Clicked")
end)



Section5:NewButton("AK-47 Ammo", "Ammo", function()
    local gun1 = require(game.Players.LocalPlayer.Backpack["AK-47"].GunStates)

gun1["damage"] = 15
gun1["MaxAmmo"] = math.huge
gun1["StoredAmmo"] = math.huge
gun1["AutoFire"] = true
gun1["FireRate"] = 0.7
gun1["Ranage"] = math.huge
gun1["Spread"] = 1
gun1["ReloadTime"] = 0.1
    
    print("Clicked")
end)


Section5:NewButton("Remington 870 Ammo", "Ammo", function()
    local gun2 = require(game.Players.LocalPlayer.Backpack["Remington 870"].GunStates)

gun2["damage"] = 15
gun2["MaxAmmo"] = math.huge
gun2["StoredAmmo"] = math.huge
gun2["AutoFire"] = true
gun2["FireRate"] = 0.7
gun2["Ranage"] = math.huge
gun2["Spread"] = 1
gun2["ReloadTime"] = 0.1

    print("Clicked")
end)


Section5:NewButton("M9 Ammo", "Ammo", function()
    local gun3 = require(game.Players.LocalPlayer.Backpack["M9"].GunStates)

gun3["damage"] = 15
gun3["MaxAmmo"] = math.huge
gun3["StoredAmmo"] = math.huge
gun3["AutoFire"] = true
gun3["FireRate"] = 0.7
gun3["Ranage"] = math.huge
gun3["Spread"] = 1
gun3["ReloadTime"] = 0.1
    print("Clicked")
end)


Section1:NewButton("If it doesn't work, click here and try again", "Fix Guns", function()
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "LocalPlayer"
}

workspace.Remote.loadchar:InvokeServer(unpack(args))

    
    print("Clicked")
end)
